name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  force_push_handler:
    types: [force_push]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://anhtran-cfe:$HF_TOKEN@huggingface.co/spaces/anhtran-cfe/bidv-sanctions-system main
