
[global]

developmentMode = false

[server]

runOnSave = true

port = 8501

enableCORS = false

enableXsrfProtection = true

[browser]

gatherUsageStats = false

serverAddress = "0.0.0.0"

[theme]

primaryColor = "#006B68"

backgroundColor = "#FFFFFF"

secondaryBackgroundColor = "#F0F2F6"

textColor = "#262730"

font = "sans serif"

